name: Build the ETHZ HCI page
run-name: ${{ github.actor }} is deploying the page 🚀
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Build the website
        run: npm run build
      - name: Push the changes
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add --all
          git commit --allow-empty --message "${{ env.CI_COMMIT_MESSAGE }}"
          git push